name: mcp-chromadb
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  # Core dependencies
  - httpx>=0.28.1
  - python-dotenv>=1.0.0
  # ML and vector database dependencies (CPU-only for containers)
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pytorch-cpu>=2.0.0  # Explicitly CPU-only
  - torchvision-cpu     # CPU-only torchvision
  - torchaudio-cpu      # CPU-only torchaudio
  - cpuonly             # Ensure CPU-only PyTorch ecosystem
  # Development tools
  - black
  - isort
  - mypy
  - pytest
  - curl
  - git
  # Pip dependencies that aren't available in conda
  - pip:
    - mcp[cli]>=1.3.0
    - chromadb>=0.4.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0